/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'service' : string,
  'customerName' : string,
  'status' : AppointmentStatus,
  'date' : string,
  'time' : string,
  'notes' : string,
  'customerId' : bigint,
}
export interface AppointmentInput {
  'service' : string,
  'customerName' : string,
  'status' : AppointmentStatus,
  'date' : string,
  'time' : string,
  'notes' : string,
  'customerId' : bigint,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface Customer {
  'id' : bigint,
  'visitCount' : bigint,
  'name' : string,
  'lastVisit' : string,
  'totalSpent' : bigint,
  'segment' : CustomerSegment,
  'phone' : string,
  'avatar' : string,
}
export interface CustomerInput {
  'visitCount' : bigint,
  'name' : string,
  'lastVisit' : string,
  'totalSpent' : bigint,
  'segment' : CustomerSegment,
  'phone' : string,
  'avatar' : string,
}
export type CustomerSegment = { 'New' : null } |
  { 'VIP' : null } |
  { 'Regular' : null } |
  { 'AtRisk' : null };
export interface DashboardStats {
  'activeNow' : bigint,
  'ordersToday' : bigint,
  'totalRevenue' : bigint,
  'totalCustomers' : bigint,
}
export interface Feedback {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : string,
  'text' : string,
  'sentiment' : Sentiment,
  'category' : FeedbackCategory,
  'customerId' : bigint,
  'rating' : bigint,
}
export type FeedbackCategory = { 'compliment' : null } |
  { 'complaint' : null } |
  { 'suggestion' : null };
export interface FeedbackInput {
  'customerName' : string,
  'createdAt' : string,
  'text' : string,
  'sentiment' : Sentiment,
  'category' : FeedbackCategory,
  'customerId' : bigint,
  'rating' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : string,
  'totalAmount' : bigint,
  'customerId' : bigint,
  'items' : string,
  'campaignType' : string,
  'aiDiscount' : bigint,
}
export interface OrderInput {
  'status' : OrderStatus,
  'createdAt' : string,
  'totalAmount' : bigint,
  'customerId' : bigint,
  'items' : string,
  'campaignType' : string,
  'aiDiscount' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'customer' : string,
  'date' : string,
  'discount' : bigint,
  'items' : string,
  'amount' : bigint,
}
export interface PaymentInput {
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'customer' : string,
  'date' : string,
  'discount' : bigint,
  'items' : string,
  'amount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Sentiment = { 'negative' : null } |
  { 'positive' : null } |
  { 'neutral' : null };
export interface _SERVICE {
  'createAppointment' : ActorMethod<[AppointmentInput], Result_1>,
  'createCustomer' : ActorMethod<[CustomerInput], Result_1>,
  'createFeedback' : ActorMethod<[FeedbackInput], Result_1>,
  'createOrder' : ActorMethod<[OrderInput], Result_1>,
  'createPayment' : ActorMethod<[PaymentInput], Result_1>,
  'deleteAppointment' : ActorMethod<[bigint], Result>,
  'deleteCustomer' : ActorMethod<[bigint], Result>,
  'deleteFeedback' : ActorMethod<[bigint], Result>,
  'deleteOrder' : ActorMethod<[bigint], Result>,
  'deletePayment' : ActorMethod<[bigint], Result>,
  'filterPayments' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<Payment>
  >,
  'getAppointment' : ActorMethod<[bigint], [] | [Appointment]>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerPayments' : ActorMethod<[string], Array<Payment>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getFeedback' : ActorMethod<[bigint], [] | [Feedback]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getPayment' : ActorMethod<[bigint], [] | [Payment]>,
  'listAppointments' : ActorMethod<[], Array<Appointment>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listPayments' : ActorMethod<[], Array<Payment>>,
  'searchPayments' : ActorMethod<[string], Array<Payment>>,
  'seedInitialData' : ActorMethod<[], undefined>,
  'updateAppointment' : ActorMethod<[bigint, AppointmentInput], Result>,
  'updateCustomer' : ActorMethod<[bigint, CustomerInput], Result>,
  'updateFeedback' : ActorMethod<[bigint, FeedbackInput], Result>,
  'updateOrder' : ActorMethod<[bigint, OrderInput], Result>,
  'updatePayment' : ActorMethod<[bigint, PaymentInput], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];