/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const AppointmentInput = IDL.Record({
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const CustomerSegment = IDL.Variant({
  'New' : IDL.Null,
  'VIP' : IDL.Null,
  'Regular' : IDL.Null,
  'AtRisk' : IDL.Null,
});
export const CustomerInput = IDL.Record({
  'visitCount' : IDL.Nat,
  'name' : IDL.Text,
  'lastVisit' : IDL.Text,
  'totalSpent' : IDL.Nat,
  'segment' : CustomerSegment,
  'phone' : IDL.Text,
  'avatar' : IDL.Text,
});
export const Sentiment = IDL.Variant({
  'negative' : IDL.Null,
  'positive' : IDL.Null,
  'neutral' : IDL.Null,
});
export const FeedbackCategory = IDL.Variant({
  'compliment' : IDL.Null,
  'complaint' : IDL.Null,
  'suggestion' : IDL.Null,
});
export const FeedbackInput = IDL.Record({
  'customerName' : IDL.Text,
  'createdAt' : IDL.Text,
  'text' : IDL.Text,
  'sentiment' : Sentiment,
  'category' : FeedbackCategory,
  'customerId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderInput = IDL.Record({
  'status' : OrderStatus,
  'createdAt' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'items' : IDL.Text,
  'campaignType' : IDL.Text,
  'aiDiscount' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const PaymentInput = IDL.Record({
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'customer' : IDL.Text,
  'date' : IDL.Text,
  'discount' : IDL.Nat,
  'items' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'method' : PaymentMethod,
  'customer' : IDL.Text,
  'date' : IDL.Text,
  'discount' : IDL.Nat,
  'items' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : AppointmentStatus,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : IDL.Nat,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'visitCount' : IDL.Nat,
  'name' : IDL.Text,
  'lastVisit' : IDL.Text,
  'totalSpent' : IDL.Nat,
  'segment' : CustomerSegment,
  'phone' : IDL.Text,
  'avatar' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'activeNow' : IDL.Nat,
  'ordersToday' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Text,
  'text' : IDL.Text,
  'sentiment' : Sentiment,
  'category' : FeedbackCategory,
  'customerId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'items' : IDL.Text,
  'campaignType' : IDL.Text,
  'aiDiscount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAppointment' : IDL.Func([AppointmentInput], [Result_1], []),
  'createCustomer' : IDL.Func([CustomerInput], [Result_1], []),
  'createFeedback' : IDL.Func([FeedbackInput], [Result_1], []),
  'createOrder' : IDL.Func([OrderInput], [Result_1], []),
  'createPayment' : IDL.Func([PaymentInput], [Result_1], []),
  'deleteAppointment' : IDL.Func([IDL.Nat], [Result], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [Result], []),
  'deleteFeedback' : IDL.Func([IDL.Nat], [Result], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [Result], []),
  'deletePayment' : IDL.Func([IDL.Nat], [Result], []),
  'filterPayments' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getFeedback' : IDL.Func([IDL.Nat], [IDL.Opt(Feedback)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'searchPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'seedInitialData' : IDL.Func([], [], []),
  'updateAppointment' : IDL.Func([IDL.Nat, AppointmentInput], [Result], []),
  'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [Result], []),
  'updateFeedback' : IDL.Func([IDL.Nat, FeedbackInput], [Result], []),
  'updateOrder' : IDL.Func([IDL.Nat, OrderInput], [Result], []),
  'updatePayment' : IDL.Func([IDL.Nat, PaymentInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const AppointmentInput = IDL.Record({
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const CustomerSegment = IDL.Variant({
    'New' : IDL.Null,
    'VIP' : IDL.Null,
    'Regular' : IDL.Null,
    'AtRisk' : IDL.Null,
  });
  const CustomerInput = IDL.Record({
    'visitCount' : IDL.Nat,
    'name' : IDL.Text,
    'lastVisit' : IDL.Text,
    'totalSpent' : IDL.Nat,
    'segment' : CustomerSegment,
    'phone' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const Sentiment = IDL.Variant({
    'negative' : IDL.Null,
    'positive' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const FeedbackCategory = IDL.Variant({
    'compliment' : IDL.Null,
    'complaint' : IDL.Null,
    'suggestion' : IDL.Null,
  });
  const FeedbackInput = IDL.Record({
    'customerName' : IDL.Text,
    'createdAt' : IDL.Text,
    'text' : IDL.Text,
    'sentiment' : Sentiment,
    'category' : FeedbackCategory,
    'customerId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderInput = IDL.Record({
    'status' : OrderStatus,
    'createdAt' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'items' : IDL.Text,
    'campaignType' : IDL.Text,
    'aiDiscount' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const PaymentInput = IDL.Record({
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'customer' : IDL.Text,
    'date' : IDL.Text,
    'discount' : IDL.Nat,
    'items' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'method' : PaymentMethod,
    'customer' : IDL.Text,
    'date' : IDL.Text,
    'discount' : IDL.Nat,
    'items' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : AppointmentStatus,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'visitCount' : IDL.Nat,
    'name' : IDL.Text,
    'lastVisit' : IDL.Text,
    'totalSpent' : IDL.Nat,
    'segment' : CustomerSegment,
    'phone' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'activeNow' : IDL.Nat,
    'ordersToday' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Text,
    'text' : IDL.Text,
    'sentiment' : Sentiment,
    'category' : FeedbackCategory,
    'customerId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'items' : IDL.Text,
    'campaignType' : IDL.Text,
    'aiDiscount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAppointment' : IDL.Func([AppointmentInput], [Result_1], []),
    'createCustomer' : IDL.Func([CustomerInput], [Result_1], []),
    'createFeedback' : IDL.Func([FeedbackInput], [Result_1], []),
    'createOrder' : IDL.Func([OrderInput], [Result_1], []),
    'createPayment' : IDL.Func([PaymentInput], [Result_1], []),
    'deleteAppointment' : IDL.Func([IDL.Nat], [Result], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [Result], []),
    'deleteFeedback' : IDL.Func([IDL.Nat], [Result], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [Result], []),
    'deletePayment' : IDL.Func([IDL.Nat], [Result], []),
    'filterPayments' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getAppointment' : IDL.Func([IDL.Nat], [IDL.Opt(Appointment)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getFeedback' : IDL.Func([IDL.Nat], [IDL.Opt(Feedback)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [IDL.Opt(Payment)], ['query']),
    'listAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'searchPayments' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
    'seedInitialData' : IDL.Func([], [], []),
    'updateAppointment' : IDL.Func([IDL.Nat, AppointmentInput], [Result], []),
    'updateCustomer' : IDL.Func([IDL.Nat, CustomerInput], [Result], []),
    'updateFeedback' : IDL.Func([IDL.Nat, FeedbackInput], [Result], []),
    'updateOrder' : IDL.Func([IDL.Nat, OrderInput], [Result], []),
    'updatePayment' : IDL.Func([IDL.Nat, PaymentInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };