/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OrderInput {
    status: OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
}
export interface Feedback {
    id: bigint;
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: Sentiment;
    category: FeedbackCategory;
    customerId: bigint;
    rating: bigint;
}
export interface AppointmentInput {
    service: string;
    customerName: string;
    status: AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
}
export interface Payment {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
}
export interface DashboardStats {
    activeNow: bigint;
    ordersToday: bigint;
    totalRevenue: bigint;
    totalCustomers: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface Order {
    id: bigint;
    status: OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
}
export interface CustomerInput {
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: CustomerSegment;
    phone: string;
    avatar: string;
}
export interface Customer {
    id: bigint;
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: CustomerSegment;
    phone: string;
    avatar: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface PaymentInput {
    status: PaymentStatus;
    method: PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
}
export interface Appointment {
    id: bigint;
    service: string;
    customerName: string;
    status: AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
}
export interface FeedbackInput {
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: Sentiment;
    category: FeedbackCategory;
    customerId: bigint;
    rating: bigint;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum CustomerSegment {
    New = "New",
    VIP = "VIP",
    Regular = "Regular",
    AtRisk = "AtRisk"
}
export enum FeedbackCategory {
    compliment = "compliment",
    complaint = "complaint",
    suggestion = "suggestion"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded"
}
export enum Sentiment {
    negative = "negative",
    positive = "positive",
    neutral = "neutral"
}
export interface backendInterface {
    createAppointment(input: AppointmentInput): Promise<Result_1>;
    createCustomer(input: CustomerInput): Promise<Result_1>;
    createFeedback(input: FeedbackInput): Promise<Result_1>;
    createOrder(input: OrderInput): Promise<Result_1>;
    createPayment(input: PaymentInput): Promise<Result_1>;
    deleteAppointment(id: bigint): Promise<Result>;
    deleteCustomer(id: bigint): Promise<Result>;
    deleteFeedback(id: bigint): Promise<Result>;
    deleteOrder(id: bigint): Promise<Result>;
    deletePayment(id: bigint): Promise<Result>;
    filterPayments(status: string | null, method: string | null): Promise<Array<Payment>>;
    getAppointment(id: bigint): Promise<Appointment | null>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomerPayments(customerName: string): Promise<Array<Payment>>;
    getDashboardStats(): Promise<DashboardStats>;
    getFeedback(id: bigint): Promise<Feedback | null>;
    getOrder(id: bigint): Promise<Order | null>;
    getPayment(id: bigint): Promise<Payment | null>;
    listAppointments(): Promise<Array<Appointment>>;
    listCustomers(): Promise<Array<Customer>>;
    listFeedbacks(): Promise<Array<Feedback>>;
    listOrders(): Promise<Array<Order>>;
    listPayments(): Promise<Array<Payment>>;
    searchPayments(queryText: string): Promise<Array<Payment>>;
    seedInitialData(): Promise<void>;
    updateAppointment(id: bigint, input: AppointmentInput): Promise<Result>;
    updateCustomer(id: bigint, input: CustomerInput): Promise<Result>;
    updateFeedback(id: bigint, input: FeedbackInput): Promise<Result>;
    updateOrder(id: bigint, input: OrderInput): Promise<Result>;
    updatePayment(id: bigint, input: PaymentInput): Promise<Result>;
}
import type { Appointment as _Appointment, AppointmentInput as _AppointmentInput, AppointmentStatus as _AppointmentStatus, Customer as _Customer, CustomerInput as _CustomerInput, CustomerSegment as _CustomerSegment, Feedback as _Feedback, FeedbackCategory as _FeedbackCategory, FeedbackInput as _FeedbackInput, Order as _Order, OrderInput as _OrderInput, OrderStatus as _OrderStatus, Payment as _Payment, PaymentInput as _PaymentInput, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Result as _Result, Result_1 as _Result_1, Sentiment as _Sentiment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAppointment(arg0: AppointmentInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_AppointmentInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_AppointmentInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomer(arg0: CustomerInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_CustomerInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_CustomerInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFeedback(arg0: FeedbackInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeedback(to_candid_FeedbackInput_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeedback(to_candid_FeedbackInput_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrder(arg0: OrderInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_OrderInput_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_OrderInput_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPayment(arg0: PaymentInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(to_candid_PaymentInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(to_candid_PaymentInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_1_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAppointment(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCustomer(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFeedback(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedback(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedback(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteOrder(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePayment(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterPayments(arg0: string | null, arg1: string | null): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPayments(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPayments(to_candid_opt_n29(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerPayments(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerPayments(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerPayments(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getFeedback(arg0: bigint): Promise<Feedback | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedback(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedback(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayment(arg0: bigint): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFeedbacks(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeedbacks();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeedbacks();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchPayments(arg0: string): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPayments(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPayments(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedInitialData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedInitialData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedInitialData();
            return result;
        }
    }
    async updateAppointment(arg0: bigint, arg1: AppointmentInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, to_candid_AppointmentInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, to_candid_AppointmentInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: bigint, arg1: CustomerInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n7(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n7(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFeedback(arg0: bigint, arg1: FeedbackInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeedback(arg0, to_candid_FeedbackInput_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeedback(arg0, to_candid_FeedbackInput_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrder(arg0: bigint, arg1: OrderInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, to_candid_OrderInput_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, to_candid_OrderInput_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePayment(arg0: bigint, arg1: PaymentInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, to_candid_PaymentInput_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, to_candid_PaymentInput_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerSegment_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerSegment): CustomerSegment {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackCategory_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackCategory): FeedbackCategory {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Feedback_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Sentiment_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sentiment): Sentiment {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Appointment]): Appointment | null {
    return value.length === 0 ? null : from_candid_Appointment_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Feedback]): Feedback | null {
    return value.length === 0 ? null : from_candid_Feedback_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n55(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PaymentStatus;
    method: _PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
}): {
    id: bigint;
    status: PaymentStatus;
    method: PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n33(_uploadFile, _downloadFile, value.status),
        method: from_candid_PaymentMethod_n35(_uploadFile, _downloadFile, value.method),
        customer: value.customer,
        date: value.date,
        discount: value.discount,
        items: value.items,
        amount: value.amount
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: string;
    customerName: string;
    status: _AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
}): {
    id: bigint;
    service: string;
    customerName: string;
    status: AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
} {
    return {
        id: value.id,
        service: value.service,
        customerName: value.customerName,
        status: from_candid_AppointmentStatus_n40(_uploadFile, _downloadFile, value.status),
        date: value.date,
        time: value.time,
        notes: value.notes,
        customerId: value.customerId
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: _CustomerSegment;
    phone: string;
    avatar: string;
}): {
    id: bigint;
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: CustomerSegment;
    phone: string;
    avatar: string;
} {
    return {
        id: value.id,
        visitCount: value.visitCount,
        name: value.name,
        lastVisit: value.lastVisit,
        totalSpent: value.totalSpent,
        segment: from_candid_CustomerSegment_n45(_uploadFile, _downloadFile, value.segment),
        phone: value.phone,
        avatar: value.avatar
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: _Sentiment;
    category: _FeedbackCategory;
    customerId: bigint;
    rating: bigint;
}): {
    id: bigint;
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: Sentiment;
    category: FeedbackCategory;
    customerId: bigint;
    rating: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        text: value.text,
        sentiment: from_candid_Sentiment_n50(_uploadFile, _downloadFile, value.sentiment),
        category: from_candid_FeedbackCategory_n52(_uploadFile, _downloadFile, value.category),
        customerId: value.customerId,
        rating: value.rating
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n57(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        items: value.items,
        campaignType: value.campaignType,
        aiDiscount: value.aiDiscount
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "refunded" in value ? PaymentStatus.refunded : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "card" in value ? PaymentMethod.card : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    VIP: null;
} | {
    Regular: null;
} | {
    AtRisk: null;
}): CustomerSegment {
    return "New" in value ? CustomerSegment.New : "VIP" in value ? CustomerSegment.VIP : "Regular" in value ? CustomerSegment.Regular : "AtRisk" in value ? CustomerSegment.AtRisk : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    negative: null;
} | {
    positive: null;
} | {
    neutral: null;
}): Sentiment {
    return "negative" in value ? Sentiment.negative : "positive" in value ? Sentiment.positive : "neutral" in value ? Sentiment.neutral : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    compliment: null;
} | {
    complaint: null;
} | {
    suggestion: null;
}): FeedbackCategory {
    return "compliment" in value ? FeedbackCategory.compliment : "complaint" in value ? FeedbackCategory.complaint : "suggestion" in value ? FeedbackCategory.suggestion : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n55(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentInput): _AppointmentInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): _CustomerInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerSegment_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerSegment): _CustomerSegment {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FeedbackCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackCategory): _FeedbackCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_FeedbackInput_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackInput): _FeedbackInput {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentInput): _PaymentInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Sentiment_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sentiment): _Sentiment {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: Sentiment;
    category: FeedbackCategory;
    customerId: bigint;
    rating: bigint;
}): {
    customerName: string;
    createdAt: string;
    text: string;
    sentiment: _Sentiment;
    category: _FeedbackCategory;
    customerId: bigint;
    rating: bigint;
} {
    return {
        customerName: value.customerName,
        createdAt: value.createdAt,
        text: value.text,
        sentiment: to_candid_Sentiment_n13(_uploadFile, _downloadFile, value.sentiment),
        category: to_candid_FeedbackCategory_n15(_uploadFile, _downloadFile, value.category),
        customerId: value.customerId,
        rating: value.rating
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
}): {
    status: _OrderStatus;
    createdAt: string;
    totalAmount: bigint;
    customerId: bigint;
    items: string;
    campaignType: string;
    aiDiscount: bigint;
} {
    return {
        status: to_candid_OrderStatus_n19(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        items: value.items,
        campaignType: value.campaignType,
        aiDiscount: value.aiDiscount
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: string;
    customerName: string;
    status: AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
}): {
    service: string;
    customerName: string;
    status: _AppointmentStatus;
    date: string;
    time: string;
    notes: string;
    customerId: bigint;
} {
    return {
        service: value.service,
        customerName: value.customerName,
        status: to_candid_AppointmentStatus_n3(_uploadFile, _downloadFile, value.status),
        date: value.date,
        time: value.time,
        notes: value.notes,
        customerId: value.customerId
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PaymentStatus;
    method: PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
}): {
    status: _PaymentStatus;
    method: _PaymentMethod;
    customer: string;
    date: string;
    discount: bigint;
    items: string;
    amount: bigint;
} {
    return {
        status: to_candid_PaymentStatus_n23(_uploadFile, _downloadFile, value.status),
        method: to_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.method),
        customer: value.customer,
        date: value.date,
        discount: value.discount,
        items: value.items,
        amount: value.amount
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: CustomerSegment;
    phone: string;
    avatar: string;
}): {
    visitCount: bigint;
    name: string;
    lastVisit: string;
    totalSpent: bigint;
    segment: _CustomerSegment;
    phone: string;
    avatar: string;
} {
    return {
        visitCount: value.visitCount,
        name: value.name,
        lastVisit: value.lastVisit,
        totalSpent: value.totalSpent,
        segment: to_candid_CustomerSegment_n9(_uploadFile, _downloadFile, value.segment),
        phone: value.phone,
        avatar: value.avatar
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerSegment): {
    New: null;
} | {
    VIP: null;
} | {
    Regular: null;
} | {
    AtRisk: null;
} {
    return value == CustomerSegment.New ? {
        New: null
    } : value == CustomerSegment.VIP ? {
        VIP: null
    } : value == CustomerSegment.Regular ? {
        Regular: null
    } : value == CustomerSegment.AtRisk ? {
        AtRisk: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sentiment): {
    negative: null;
} | {
    positive: null;
} | {
    neutral: null;
} {
    return value == Sentiment.negative ? {
        negative: null
    } : value == Sentiment.positive ? {
        positive: null
    } : value == Sentiment.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FeedbackCategory): {
    compliment: null;
} | {
    complaint: null;
} | {
    suggestion: null;
} {
    return value == FeedbackCategory.compliment ? {
        compliment: null
    } : value == FeedbackCategory.complaint ? {
        complaint: null
    } : value == FeedbackCategory.suggestion ? {
        suggestion: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == AppointmentStatus.scheduled ? {
        scheduled: null
    } : value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
